language: ruby
script: "./build.sh"
branches:
  only:
  - middleman
rvm:
- 2.1.2
env:
  global:
    secure: d8YGbb/rCcV6yrxPy7E9BEbRmXIn33SqqAXPRIO2Bls5jT6/HKsQbFgxWyO3gr9AO4mSSP9Q5njP6umwwqjy4nvf7inxrn06/N1XvNKEn+FbWQOZWxWxj/96r3ZbtInSkEMD525ubEpbYiMNmPc94jlx/83hdJjMa4Ojqrrvdbzl3seWurHnR5x5ilVx4qBFYlqZ+4V3hx15a4b1xjK14MswC1cOk2WnI6McNbdtb4CmeteEwkM53q1rDb8c5r7P5jcQ4A/f+RdSMw0YsId07SFWM/NnFVSVcnJDauuab1wX+vSUNZkhPZBDiENMskgklBUCladoeGDirm2ah1TmKjQm0Y7/aznaeq4lm5q6EDZ2IdDZeZ42KAnX5MA6Pi2jci3aVe2j32lFCterncpQSBENiS7F7v/aGhWEwgFqkHwe9fx00tVyrAKHS9Y52J3IexZxH3QI2w6aINS7RlBycNLoY1JU/T3fPWU/bAKS4c+KjLvTs/0Ww7IXMck+TSVIuufw7ZXFS1YKnKu7MfsI0F1t1+cZBhYPRvMkimnIypv2bsAogbdeVnJ7egEzec799yxRY6lXcmXiq9TwzlX2ysL3nwPhfap0juXX89IAo6JErhQUxRaxPhzGvypbUgau3YYol3dgLgCOZtOmfXuC4U0yQS3r84c8fVXiojduizA=
